apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: prod
      app.kubernetes.io/name: milestone-timeline

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./secret.yaml

images:
  - name: cr.hday/image
    newName: cr.hday.io/hday/milestone-timeline
    newTag: "r21817508657"
